services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always

# sample queries for CMD and GITBASH (the previous line of code is not yet updated)
###
# docker run -it \
#  -e POSTGRES_USER="root" \
#  -e POSTGRES_PASSWORD="root" \
#  -e POSTGRES_DB="root" \
#  -v D:/Users/rmanuel/Documents/GitHub/data-engineering-zoomcamp-2025/Week\ 1/2_DOCKER_SQL/ny_taxi_postgres_data:/var/lib/postgresql/data \
#  -p 5432:5432 \
#  postgres:13
#
#  docker run -it POSTGRES_USER=root -e POSTGRES_PASSWORD=root -e POSTGRES_DB=root -v "D:/Users/rmanuel/Documents/GitHub/data-engineering-zoomcamp-2025/Week\ 1/2_DOCKER_SQL/#ny_taxi_postgres_data:/var/lib/postgresql/data" -p 5432:5432 postgres:13
